#!/bin/bash
for f in AM2302.py uploader.sh cam.sh pictureloader.sh
do
  cp $f /usr/local/bin/${f}
done

fgrep phytonat /etc/hosts && echo "You forgot to add phytonaut to /etc/hosts."

crontab -u root cron.tab
