#!/bin/bash
for f in AM2302.py cp uploader.sh cam.sh
do
  cp $f /usr/local/bin/${f}
done

fgrep phytonat /etc/hosts && cat <<EOF

"You forgot to add phytonaut to /etc/hosts."

EOF

crontab -u root cron.tab
