#!/usr/bin/python
#
#   = = A C T U A T O R = =
#
# This module sets the GPIO pins which in
# turn flipps the relays.  The relays are
# bistable, so there is no need to hold the pins
# up or down.
#
# The desired values are read from the files
# /tmp/desired_relay1 though /tmp/desired_relay8
#
# The values can be:
# on         -- flipps the relay to on.
#               *Used for long (aka more than a
#                minute) activities.  Usefull for
#                lighting and heating.
# off        -- flipps the relay to off.
import ConfigParser
import Relay

if __name__ == '__main__':
    pinList = Relay.get_pinlist()
    state = Relay.get_relay_state()
    Relay.relay_init(pinList)

    for i in range(0, len(pinList)):
        Relay.set_pin(pinList[i], state[i])
