#!/usr/bin/python
## Analyze what needs to be done.
import datetime
import time

actual_temperature_file='/tmp/actual_temperature'
actual_humidity_file='/tmp/actual_humudity'
actual_co2_file='/tmp/actual_co2'
desired_temperature_file='/tmp/desired_temperature'
desired_humidity_file='/tmp/desired_humudity'
desired_co2_file='/tmp/desired_co2'
desired_relay_file='/tmp/desired_relay'
desired_light_file='/tmp/desired_light'

now = datetime.datetime.now()

def num(s):
    try:
        return int(s)
    except ValueError:
        return float(s)

def set_relay(file, value):
    with open(file, 'w') as f:
        f.write(value)

def maintain_range(desiredfile, actualfile, relayfile):
    '''Keep a value within a range.'''
    try:
        with open(actualfile, 'r') as f:
            actual = num(f.read().strip())
    except:
        return None             # No actual value.  Abort
    try:
        with open(desiredfile, 'r') as f:
            minimum = num(f.readline().strip())
            maximum = num(f.readline().strip())
    except:
        return None             # No desired value.  Abort
    
    if (actual < minimum):
        set_relay(relayfile, 'on')
    elif actual > maximum:
        set_relay(relayfile, 'off')

## Relay 1, light
with open('/tmp/now', 'w') as f:
    f.write("%f\n" % (time.time()))

maintain_range(desired_light_file, '/tmp/now', '/tmp/desired_relay1')

## Relay 2 Heat
maintain_range(desired_temperature_file, actual_temperature_file, '/tmp/desired_relay2')

## Relay 3 Humidity
maintain_range(desired_humidity_file, actual_humidity_file, '/tmp/desired_relay3')

## Relay 4 CO2
# maintain_range(desired_co2_file, actual_co2_file, '/tmp/desired_relay4')
