#!/bin/bash
for f in temp.py tempuploader.sh cam.sh camuploader.sh
do
  cp $f /usr/local/bin/${f}
done

fgrep phytonat /etc/hosts && echo "You forgot to add phytonaut to /etc/hosts."

crontab -u root cron.tab
