#!/bin/bash
for f in temp.py tempuploader.py cam.sh camuploader.sh
do
  sudo cp $f /usr/local/bin/${f}
done

fgrep phytonat /etc/hosts && echo "You forgot to add phytonaut to /etc/hosts."

sudo crontab -u root cron.tab
