#!/usr/bin/python                                                                                                   
import RPi.GPIO as GPIO
import time
import sys
import Relay

if __name__ == '__main__':
    pinList = Relay.get_pinlist()
    Relay.relay_init(pinList)

    i = pinList[int(sys.argv[1])-1]
    Relay.set_pin(i, sys.argv[2])
