#!/bin/bash
## Every day, plot a weeks worth of data

P=/home/ec2-user/tomatopi/serverside
# P=/home/jarl/ws/plantbiogroup/tomatopi/serverside

NAME=`date --date='TZ="America/Los_Angeles" now' +%Ywk%V`

plot_graph()
{
    mkdir -p ${P}/static/${1}/
    find ${P}/static/${1}/ -type f -mtime +32 -delete
    cat<<-EOF | gnuplot
	set xdata time
	set timefmt "${TIMEFMT}"
	set format x "%a %d %b"
	set datafile separator ","
	set grid
	set xlabel "Day of Week"
 	set output "${P}/static/${1}/${NAME}.png"
	set terminal png size 1800,600
	plot ["${THEN}":"${NOW}"] "${P}/measurements" using 1:2 with lines title "Temp (°C)", "${P}/measurements" using 1:3 with lines title "Humidity (%)", "${P}/measurements" using 1:4 with lines title "CO2(ppm/10)"
EOF
}

TIMEFMT="%Y-%m-%dT%H:%M:%S"
NOW=`/bin/date +"${TIMEFMT}"`
THEN=`/bin/date --date="last week" +"${TIMEFMT}"`

plot_graph "weekly"
