#!/bin/bash
## Every hour, plot a days worth of data

# P=/home/ec2-user/tomatopi/serverside
P=/home/jarl/ws/plantbiogroup/tomatopi/serverside

NAME=`date +%Y-%m-%d`

plot_graph()
{
    mkdir -p ${P}/static/${1}/
    find ${P}/static/${1}/ -type f -mtime +8 -delete
    cat<<-EOF | gnuplot
	set xdata time
	set timefmt "${TIMEFMT}"
	set format x "%H:%M"
	set timefmt "${TIMEFMT}"
	set datafile separator ","
	set grid
	set xlabel "Time of day (24h)"
 	set output "${P}/static/${1}/${NAME}.png"
	set terminal png size 1800,600
	plot ["${THEN}":"${NOW}"] "${P}/measurements" using 1:2 with lines title "Temp (°C)", "${P}/measurements" using 1:3 with lines title "Humidity (%)", "${P}/measurements" using 1:4 with lines title "CO2(ppm/10)"
EOF
}


TIMEFMT="%Y-%m-%dT%H:%M:%S"
NOW=`/bin/date +"${TIMEFMT}"`
THEN=`/bin/date --date="yesterday" +"${TIMEFMT}"`

plot_graph "daily"
